# Generated by Django 5.2.7 on 2025-10-22 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nume_categorie', models.CharField(max_length=100, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('tip_material', models.CharField(max_length=100, unique=True)),
                ('culoare', models.CharField(blank=True, max_length=50, null=True)),
                ('rezistent_la_apa', models.BooleanField(default=False)),
                ('textura', models.CharField(choices=[('NETE', 'Netedă'), ('RUG', 'Rugosită'), ('MAT', 'Mată'), ('STR', 'Strălucitoare'), ('TEXT', 'Texturată')], default='NETE', max_length=4)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiale',
            },
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id_producator', models.AutoField(primary_key=True, serialize=False)),
                ('nume_producator', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producător',
                'verbose_name_plural': 'Producători',
            },
        ),
        migrations.CreateModel(
            name='SetAccessorii',
            fields=[
                ('id_set', models.AutoField(primary_key=True, serialize=False)),
                ('nume_set', models.CharField(max_length=100, unique=True)),
                ('nr_piese', models.IntegerField(default=1)),
                ('compatibilitate', models.CharField(max_length=200)),
                ('editie_speciala', models.BooleanField(default=False)),
                ('tip_accesorii', models.CharField(choices=[('SCUL', 'Sculă'), ('UNGE', 'Unelte'), ('VOP', 'Vopsele'), ('DEC', 'Decalcomanii'), ('ALT', 'Altele')], default='SCUL', max_length=4)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Set Accesorii',
                'verbose_name_plural': 'Seturi Accesorii',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Acces',
                'verbose_name_plural': 'Loguri Acces',
            },
        ),
        migrations.CreateModel(
            name='Figurina',
            fields=[
                ('id_figurina', models.AutoField(primary_key=True, serialize=False)),
                ('nume_figurina', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('greutate', models.DecimalField(decimal_places=2, help_text='Greutate în kg', max_digits=6)),
                ('stoc_disponibil', models.IntegerField(default=0)),
                ('data_lansare', models.DateField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('tara_origine', models.CharField(choices=[('USA', 'Statele Unite'), ('GER', 'Germania'), ('RUS', 'Rusia'), ('UK', 'Marea Britanie'), ('JAP', 'Japonia'), ('FR', 'Franța')], default='USA', max_length=3)),
                ('stare', models.CharField(choices=[('NOU', 'Nou'), ('FOL', 'Folosit'), ('COL', 'Colecție'), ('RES', 'Restaurat')], default='NOU', max_length=3)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.categorie')),
            ],
            options={
                'verbose_name': 'Figurină',
                'verbose_name_plural': 'Figurine',
            },
        ),
        migrations.CreateModel(
            name='FigurinaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procentaj', models.DecimalField(decimal_places=2, default=100.0, help_text='Procentajul materialului în figurină', max_digits=5)),
                ('figurina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.figurina')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.material')),
            ],
            options={
                'unique_together': {('figurina', 'material')},
            },
        ),
        migrations.AddField(
            model_name='figurina',
            name='materiale',
            field=models.ManyToManyField(through='proiectapp.FigurinaMaterial', to='proiectapp.material'),
        ),
        migrations.AddField(
            model_name='figurina',
            name='id_producator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.producator'),
        ),
        migrations.CreateModel(
            name='Seria',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('nume_serie', models.CharField(max_length=100)),
                ('an_lansare', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('descriere', models.TextField(blank=True, null=True)),
                ('disponibilitate', models.BooleanField(default=True)),
                ('scala', models.CharField(choices=[('1:35', '1:35'), ('1:48', '1:48'), ('1:72', '1:72'), ('1:100', '1:100'), ('1:144', '1:144')], default='1:35', max_length=10)),
                ('id_producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.producator')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Serii',
            },
        ),
        migrations.AddField(
            model_name='figurina',
            name='id_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.seria'),
        ),
        migrations.CreateModel(
            name='FigurinaSetAccesorii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_asociere', models.DateTimeField(auto_now_add=True)),
                ('compatibil_perfect', models.BooleanField(default=True)),
                ('figurina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.figurina')),
                ('set_accesorii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.setaccessorii')),
            ],
            options={
                'unique_together': {('figurina', 'set_accesorii')},
            },
        ),
        migrations.AddField(
            model_name='figurina',
            name='seturi_accesorii',
            field=models.ManyToManyField(through='proiectapp.FigurinaSetAccesorii', to='proiectapp.setaccessorii'),
        ),
    ]
