# Generated by Django 5.2.7 on 2025-11-12 16:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nume_categorie', models.CharField(max_length=100, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('culoare', models.CharField(default='#333333', help_text='Culoarea categoriei', max_length=7)),
                ('culoare_activa', models.CharField(default='#007BFF', help_text='Culoarea pentru hover', max_length=7)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('tip_material', models.CharField(max_length=100, unique=True)),
                ('culoare', models.CharField(blank=True, max_length=50, null=True)),
                ('rezistent_la_apa', models.BooleanField(default=False)),
                ('textura', models.CharField(choices=[('NETE', 'Neteda'), ('MAT', 'Mata'), ('STR', 'Stralucitoare'), ('TEXT', 'Texturată')], default='NETE', max_length=4)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiale',
            },
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id_producator', models.AutoField(primary_key=True, serialize=False)),
                ('nume_producator', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producator',
                'verbose_name_plural': 'Producatori',
            },
        ),
        migrations.CreateModel(
            name='SetAccessorii',
            fields=[
                ('id_set', models.AutoField(primary_key=True, serialize=False)),
                ('nume_set', models.CharField(max_length=100, unique=True)),
                ('nr_piese', models.IntegerField(default=1)),
                ('compatibilitate', models.CharField(max_length=200)),
                ('editie_speciala', models.BooleanField(default=False)),
                ('tip_accesorii', models.CharField(choices=[('CAM', 'Camuflaj'), ('UNEL', 'Unelte'), ('VOP', 'Vopsele'), ('LANT', 'Lanturi'), ('ALT', 'Altele')], default='CAM', max_length=4)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Set Accesorii',
                'verbose_name_plural': 'Seturi Accesorii',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, help_text='Numărul de telefon (opțional).', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Numărul de telefon trebuie să fie în formatul: '+999999999'. Până la 15 cifre permise.", regex='^\\+?1?\\d{9,15}$')])),
                ('data_nasterii', models.DateField(blank=True, help_text='Data nașterii (opțional).', null=True)),
                ('adresa_strada', models.CharField(blank=True, max_length=255, null=True)),
                ('adresa_oras', models.CharField(blank=True, max_length=100, null=True)),
                ('adresa_judet', models.CharField(blank=True, max_length=100, null=True)),
                ('adresa_cod_postal', models.CharField(blank=True, help_text='Codul poștal (opțional).', max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Acces',
                'verbose_name_plural': 'Loguri Acces',
            },
        ),
        migrations.CreateModel(
            name='Figurina',
            fields=[
                ('id_figurina', models.AutoField(primary_key=True, serialize=False)),
                ('nume_figurina', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('greutate', models.DecimalField(decimal_places=2, help_text='Greutate in kg', max_digits=6)),
                ('stoc_disponibil', models.IntegerField(default=0)),
                ('data_lansare', models.DateField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('tara_origine', models.CharField(choices=[('USA', 'Statele Unite'), ('GER', 'Germania'), ('RUS', 'Rusia'), ('UK', 'Marea Britanie'), ('JAP', 'Japonia'), ('SU', 'Suedia'), ('CHN', 'China'), ('FRA', 'Franta'), ('ITA', 'Italia')], default='None', max_length=3)),
                ('stare', models.CharField(choices=[('NOU', 'Nou'), ('FOL', 'Folosit'), ('COL', 'Colectie'), ('RES', 'Restaurat')], default='NOU', max_length=3)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='produse_imagini/')),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.categorie')),
            ],
            options={
                'verbose_name': 'Figurina',
                'verbose_name_plural': 'Figurine',
            },
        ),
        migrations.CreateModel(
            name='FigurinaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procentaj', models.DecimalField(decimal_places=2, default=100.0, help_text='Procentajul materialului în figurina', max_digits=5)),
                ('figurina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.figurina')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.material')),
            ],
            options={
                'unique_together': {('figurina', 'material')},
            },
        ),
        migrations.AddField(
            model_name='figurina',
            name='materiale',
            field=models.ManyToManyField(through='proiectapp.FigurinaMaterial', to='proiectapp.material'),
        ),
        migrations.AddField(
            model_name='figurina',
            name='id_producator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.producator'),
        ),
        migrations.CreateModel(
            name='Seria',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('nume_serie', models.CharField(max_length=100)),
                ('an_lansare', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('descriere', models.TextField(blank=True, null=True)),
                ('disponibilitate', models.BooleanField(default=True)),
                ('scala', models.CharField(choices=[('1:35', '1:35'), ('1:48', '1:48'), ('1:72', '1:72'), ('1:100', '1:100'), ('1:144', '1:144')], default='1:35', max_length=10)),
                ('imagine_serie', models.ImageField(blank=True, null=True, upload_to='serii_imagini/', verbose_name='Imagine Serie')),
                ('id_producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.producator')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Serii',
            },
        ),
        migrations.AddField(
            model_name='figurina',
            name='id_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.seria'),
        ),
        migrations.CreateModel(
            name='FigurinaSetAccesorii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_asociere', models.DateTimeField(auto_now_add=True)),
                ('compatibil_perfect', models.BooleanField(default=True)),
                ('figurina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.figurina')),
                ('set_accesorii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectapp.setaccessorii')),
            ],
            options={
                'unique_together': {('figurina', 'set_accesorii')},
            },
        ),
        migrations.AddField(
            model_name='figurina',
            name='seturi_accesorii',
            field=models.ManyToManyField(through='proiectapp.FigurinaSetAccesorii', to='proiectapp.setaccessorii'),
        ),
    ]
