# Generated by Django 5.2.7 on 2025-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figurina',
            options={'verbose_name': 'Figurina', 'verbose_name_plural': 'Figurine'},
        ),
        migrations.AlterModelOptions(
            name='producator',
            options={'verbose_name': 'Producator', 'verbose_name_plural': 'Producatori'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='culoare',
            field=models.CharField(default='#333333', help_text='#1F5D7D', max_length=7),
        ),
        migrations.AlterField(
            model_name='figurina',
            name='greutate',
            field=models.DecimalField(decimal_places=2, help_text='Greutate in kg', max_digits=6),
        ),
        migrations.AlterField(
            model_name='figurina',
            name='stare',
            field=models.CharField(choices=[('NOU', 'Nou'), ('FOL', 'Folosit'), ('COL', 'Colectie'), ('RES', 'Restaurat')], default='NOU', max_length=3),
        ),
        migrations.AlterField(
            model_name='figurina',
            name='tara_origine',
            field=models.CharField(choices=[('USA', 'Statele Unite'), ('GER', 'Germania'), ('RUS', 'Rusia'), ('UK', 'Marea Britanie'), ('JAP', 'Japonia'), ('SU', 'Suedia'), ('CHN', 'China'), ('FRA', 'Franta'), ('ITA', 'Italia')], default='USA', max_length=3),
        ),
        migrations.AlterField(
            model_name='figurinamaterial',
            name='procentaj',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Procentajul materialului în figurina', max_digits=5),
        ),
        migrations.AlterField(
            model_name='material',
            name='textura',
            field=models.CharField(choices=[('NETE', 'Neteda'), ('MAT', 'Mata'), ('STR', 'Stralucitoare'), ('TEXT', 'Texturată')], default='NETE', max_length=4),
        ),
        migrations.AlterField(
            model_name='setaccessorii',
            name='tip_accesorii',
            field=models.CharField(choices=[('CAM', 'Camuflaj'), ('UNEL', 'Unelte'), ('VOP', 'Vopsele'), ('LANT', 'Lanturi'), ('ALT', 'Altele')], default='CAM', max_length=4),
        ),
    ]
