# Generated by Django 5.2.7 on 2025-11-25 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adresa_cod_postal',
            field=models.CharField(blank=True, help_text='Codul postal (optional).', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_nasterii',
            field=models.DateField(blank=True, help_text='Data nasterii (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefon',
            field=models.CharField(blank=True, help_text='Numarul de telefon (optional).', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Numarul de telefon trebuie sa fie in formatul: '+999999999'. Pana la 15 cifre permise.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
