# Generated by Django 5.2.7 on 2025-10-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0002_alter_figurina_options_alter_producator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurina',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='produse_imagini/'),
        ),
    ]
