# Generated by Django 5.2.7 on 2025-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0003_figurina_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
