# Generated by Django 5.2.7 on 2025-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0003_promotie_vizualizare'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False, help_text='Daca este bifat, utilizatorul nu se poate loga pe site.'),
        ),
    ]
