# Generated by Django 5.2.7 on 2025-11-04 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0004_accesslog_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='culoare_activa',
            field=models.CharField(default='#007BFF', help_text='Culoarea pentru hover/click, ex. #FFC107', max_length=7),
        ),
        migrations.AlterField(
            model_name='figurina',
            name='tara_origine',
            field=models.CharField(choices=[('USA', 'Statele Unite'), ('GER', 'Germania'), ('RUS', 'Rusia'), ('UK', 'Marea Britanie'), ('JAP', 'Japonia'), ('SU', 'Suedia'), ('CHN', 'China'), ('FRA', 'Franta'), ('ITA', 'Italia')], default='None', max_length=3),
        ),
        migrations.AlterField(
            model_name='seria',
            name='an_lansare',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
