# Generated by Django 5.2.7 on 2025-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0005_categorie_culoare_activa_alter_figurina_tara_origine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seria',
            name='imagine_serie',
            field=models.ImageField(blank=True, null=True, upload_to='serii_imagini/', verbose_name='Imagine Serie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='culoare',
            field=models.CharField(default='#333333', help_text='Culoarea categoriei', max_length=7),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='culoare_activa',
            field=models.CharField(default='#007BFF', help_text='Culoarea pentru hover', max_length=7),
        ),
    ]
