# Generated by Django 5.2.7 on 2025-11-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0006_seria_imagine_serie_alter_categorie_culoare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seria',
            name='icon_fa',
            field=models.CharField(blank=True, help_text="Clasa Font Awesome, ex: 'fas fa-flag' sau 'fas fa-globe'", max_length=50, null=True),
        ),
    ]
