# Generated by Django 5.2.7 on 2025-11-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proiectapp', '0007_seria_icon_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seria',
            name='icon_fa',
        ),
    ]
